### ISSUE TITLE
Pandas:unknown_codepage_21010

### ISSUE THREAD

**Issue by danielliu920506** [wireservice/csvkit#1013]
I tried to load a .xls file with pandas.ExcelFile and received a error message below:
Traceback (most recent call last):
ERROR *** codepage 21010 -> encoding 'unknown_codepage_21010' -> LookupError: unknown encoding: unknown_codepage_21010
  File "C:/Users/yiwei.liu/PycharmProjects/untitled/Project1.py", line 9, in <module>
    file_WMG = pd.ExcelFile('C:/Users/yiwei.liu/Dropbox/2019 WMG project/test shipment prepare/job_summary_22-Jan-2019.xls')
  File "C:\Users\yiwei.liu\PycharmProjects\untitled\venv\lib\site-packages\pandas\io\excel.py", line 394, in __init__
    self.book = xlrd.open_workbook(self._io)
  File "C:\Users\yiwei.liu\PycharmProjects\untitled\venv\lib\site-packages\xlrd\__init__.py", line 157, in open_workbook
    ragged_rows=ragged_rows,
  File "C:\Users\yiwei.liu\PycharmProjects\untitled\venv\lib\site-packages\xlrd\book.py", line 117, in open_workbook_xls
    bk.parse_globals()
  File "C:\Users\yiwei.liu\PycharmProjects\untitled\venv\lib\site-packages\xlrd\book.py", line 1217, in parse_globals
    self.handle_codepage(data)
  File "C:\Users\yiwei.liu\PycharmProjects\untitled\venv\lib\site-packages\xlrd\book.py", line 839, in handle_codepage
    self.derive_encoding()
  File "C:\Users\yiwei.liu\PycharmProjects\untitled\venv\lib\site-packages\xlrd\book.py", line 820, in derive_encoding
    unicode(b'trial', self.encoding)
  File "C:\Users\yiwei.liu\PycharmProjects\untitled\venv\lib\site-packages\xlrd\timemachine.py", line 31, in <lambda>
    unicode = lambda b, enc: b.decode(enc)
LookupError: unknown encoding: unknown_codepage_21010

Can somebody help me with this issue?
Thanks a lot!

**Comment by jpmckinney** [comment]
Sorry, this is not the pandas project; please report the issue there.
