### ISSUE TITLE
Test suite fails in tests.test_utilities.test_sql2csv.TestSQL2CSV

### ISSUE THREAD

**Issue by mcepl** [wireservice/csvkit#1027]
When running the test suite (1.0.4 from the release tarball) while building packages for openSUSE, I get these failing tests ([complete build log](https://github.com/wireservice/csvkit/files/3112675/log.txt)):
```
[   44s] 
[   44s] ======================================================================
[   44s] FAIL: test_before_after_insert (tests.test_utilities.test_csvsql.TestCSVSQL)
[   44s] ----------------------------------------------------------------------
[   44s] Traceback (most recent call last):
[   44s]   File "/home/abuild/rpmbuild/BUILD/csvkit-1.0.4/tests/test_utilities/test_csvsql.py", line 200, in test_before_after_insert
[   44s]     self.assertEqual(output, 'a,b,c\n1,2,3\n0,5,6\n')
[   44s] AssertionError: 'a,b,c\n1,2.0,3.0\n0,5.0,6.0\n' != 'a,b,c\n1,2,3\n0,5,6\n'
[   44s] 
[   44s] ======================================================================
[   44s] FAIL: test_linenumbers (tests.test_utilities.test_sql2csv.TestSQL2CSV)
[   44s] ----------------------------------------------------------------------
[   44s] Traceback (most recent call last):
[   44s]   File "/home/abuild/rpmbuild/BUILD/csvkit-1.0.4/tests/test_utilities/test_sql2csv.py", line 140, in test_linenumbers
[   44s]     self.assertTrue('1,1,2,3' in csv)
[   44s] AssertionError: False is not true
[   44s] 
[   44s] ======================================================================
[   44s] FAIL: test_no_header_row (tests.test_utilities.test_sql2csv.TestSQL2CSV)
[   44s] ----------------------------------------------------------------------
[   44s] Traceback (most recent call last):
[   44s]   File "/home/abuild/rpmbuild/BUILD/csvkit-1.0.4/tests/test_utilities/test_sql2csv.py", line 133, in test_no_header_row
[   44s]     self.assertTrue('1,2,3' in csv)
[   44s] AssertionError: False is not true
[   44s] 
[   44s] ======================================================================
[   44s] FAIL: test_unicode (tests.test_utilities.test_sql2csv.TestSQL2CSV)
[   44s] ----------------------------------------------------------------------
[   44s] Traceback (most recent call last):
[   44s]   File "/home/abuild/rpmbuild/BUILD/csvkit-1.0.4/tests/test_utilities/test_sql2csv.py", line 126, in test_unicode
[   44s]     self.assertEqual(csv.strip(), expected)
[   44s] AssertionError: 'foo,bar,baz\n1.0,2.0,3\n4.0,5.0,\xca\xa4' != 'foo,bar,baz\n1,2,3\n4,5,\xca\xa4'
[   44s] 
[   44s] ----------------------------------------------------------------------
[   44s] Ran 256 tests in 28.108s
[   44s] 
[   44s] FAILED (failures=4)
[   44s] error: Bad exit status from /var/tmp/rpm-tmp.2kODRl (%check)
[   44s] 
[   44s] 
[   44s] RPM build errors:
[   44s]     Bad exit status from /var/tmp/rpm-tmp.2kODRl (%check)
[   44s] 
[   44s] milic failed "build python-csvkit.spec" at Wed Apr 24 13:56:25 UTC 2019.
[   44s]
```

**Comment by jpmckinney** [comment]
Thanks! I've now corrected the test failures in the unreleased 1.0.5. Let me know if I should make a release so that the tests pass while building packages for openSUSE.
