### ISSUE TITLE
Module call error from folder 

### ISSUE THREAD

**Issue by Eswar03** [wireservice/csvkit#1042]
I am getting the following message  like  csvkit.utilities.csvlook is not able to recognize as folder names. It is same for     from csvkit.cli import CSVKitUtility.

Please let me know any workaround in place. 

Traceback (most recent call last):
  File "/usr/local/bin/csvlook", line 7, in <module>
    from csvkit.utilities.csvlook import launch_new_instance
  File "/usr/local/lib/python3.6/site-packages/csvkit/utilities/csvlook.py", line 5, in <module>
    from csvkit.cli import CSVKitUtility
  File "/usr/local/lib/python3.6/site-packages/csvkit/cli.py", line 4, in <module>
    import bz2
  File "/usr/local/lib/python3.6/bz2.py", line 23, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

**Comment by jpmckinney** [comment]
This is an issue with your Python installation, e.g. https://stackoverflow.com/questions/12806122/missing-python-bz2-module
