### ISSUE TITLE
csvstat not working.

### ISSUE THREAD

**Issue by AnkurBegining** [wireservice/csvkit#1055]
I am trying to run csvstat on a simple CSV file containing sales data. I have run using `csvstat -v {csv_file_path}`. It is showing some random error. We are trying this very every other CSV we have. The same issue is being raised. We are very glad to use an awesome project in our codebase but got stuck here. 

```
Traceback (most recent call last):
  File "-----------------------/venv/bin/csvstat", line 11, in <module>
    load_entry_point('csvkit==1.0.4', 'console_scripts', 'csvstat')()
  File "-----------------------/venv/lib64/python3.6/site-packages/csvkit/utilities/csvstat.py", line 341, in launch_new_instance
    utility.run()
  File "-----------------------/venv/lib64/python3.6/site-packages/csvkit/cli.py", line 118, in run
    self.main()
  File "-----------------------/venv/lib64/python3.6/site-packages/csvkit/utilities/csvstat.py", line 140, in main
    **self.reader_kwargs
  File "-----------------------/venv/lib64/python3.6/site-packages/agate/table/from_csv.py", line 88, in from_csv
    return Table(rows, column_names, column_types, row_names=row_names)
  File "-----------------------/venv/lib64/python3.6/site-packages/agate/table/__init__.py", line 109, in __init__
    self._column_types = column_types.run(rows, self._column_names)
  File "-----------------------/venv/lib64/python3.6/site-packages/agate/type_tester.py", line 110, in run
    if len(row) > i and not column_type.test(row[i]):
  File "-----------------------/venv/lib64/python3.6/site-packages/agate/data_types/base.py", line 29, in test
    self.cast(d)
  File "-----------------------/venv/lib64/python3.6/site-packages/agate/data_types/date.py", line 76, in cast
    (value, ctx, _, _, matched_text), = self.parser.nlp(d, sourceTime=ZERO_DT)
  File "-----------------------/venv/lib64/python3.6/site-packages/parsedatetime/__init__.py", line 2233, in nlp
    version)
  File "-----------------------/venv/lib64/python3.6/site-packages/parsedatetime/__init__.py", line 1844, in parse
    retS, retTime, matched = parseMeth(s, sourceTime)
  File "-----------------------/venv/lib64/python3.6/site-packages/parsedatetime/__init__.py", line 1408, in _partialParseQUnits
    sourceTime = self._evalQUnits(parseStr, sourceTime)
  File "-----------------------/venv/lib64/python3.6/site-packages/parsedatetime/__init__.py", line 1100, in _evalQUnits
    sourceTime = self._buildTime(sourceTime, quantity, modifier, units)
  File "-----------------------/venv/lib64/python3.6/site-packages/parsedatetime/__init__.py", line 389, in _buildTime
    ctx.updateAccuracy(realunit)
  File "-----------------------/venv/lib64/python3.6/site-packages/parsedatetime/context.py", line 137, in updateAccuracy
    acc = self._ACCURACY_REVERSE_MAPPING[acc]
KeyError: 's'
```

[store.csv.zip](https://github.com/wireservice/csvkit/files/4045481/store.csv.zip)
 I have also attached the file. Please help us in this.

**Comment by jpmckinney** [comment]
This is caused by a bug in parsedatetime 2.5 https://github.com/bear/parsedatetime/pull/233

Do `pip install parsedatetime<2.5` until that bug is fixed.
