### ISSUE TITLE
Installation on Ubuntu 20.04 - cannot find mysql-connector-python

### ISSUE THREAD

**Issue by brianjcohen** [wireservice/csvkit#1102]
I have tried this every possible way. Following the documented installation instructions, I ran:

```
pip install csvkit
pip install mysql-connector-python
csvsql -v mysql://user:password@host/db --insert file.csv
```

This results in the following, which seems to suggest that it's failing to load or make use of SQLAlchemy.   Any help would be greatly appreciated.

```
Traceback (most recent call last):
  File "/home/brian/.local/bin/csvsql", line 8, in <module>
    sys.exit(launch_new_instance())
  File "/home/brian/.local/lib/python2.7/site-packages/csvkit/utilities/csvsql.py", line 221, in launch_new_instance
    utility.run()
  File "/home/brian/.local/lib/python2.7/site-packages/csvkit/cli.py", line 118, in run
    self.main()
  File "/home/brian/.local/lib/python2.7/site-packages/csvkit/utilities/csvsql.py", line 110, in main
    raise ImportError('You don\'t appear to have the necessary database backend installed for connection string you\'re trying to use. Available backends include:\n\nPostgresql:\tpip install psycopg2\nMySQL:\t\tpip install mysql-connector-python\n\nFor details on connection strings and other backends, please see the SQLAlchemy documentation on dialects at: \n\nhttp://www.sqlalchemy.org/docs/dialects/\n\n')
ImportError: You don't appear to have the necessary database backend installed for connection string you're trying to use. Available backends include:

Postgresql:     pip install psycopg2
MySQL:          pip install mysql-connector-python

For details on connection strings and other backends, please see the SQLAlchemy documentation on dialects at: 

http://www.sqlalchemy.org/docs/dialects/
```

**Comment by sido420** [comment]
Having the same issue on Mac and Centos container inside a virtual env.

**Comment by sido420** [comment]
I have already tried 
```
(csvkit) sh-4.4# ARCHFLAGS="-arch i386" pip install --upgrade mysql-connector-python
Requirement already satisfied: mysql-connector-python in /csvkit/lib64/python3.6/site-packages (8.0.22)
Requirement already satisfied: protobuf>=3.0.0 in /csvkit/lib64/python3.6/site-packages (from mysql-connector-python) (3.14.0)
Requirement already satisfied: six>=1.9 in /csvkit/lib/python3.6/site-packages (from protobuf>=3.0.0->mysql-connector-python) (1.15.0)
(csvkit) sh-4.4# 
(csvkit) sh-4.4# csvsql --insert --create-if-not-exists --chunk-size 4096  --db mysql://test@localhost/test 123123.csv
ImportError: You don't appear to have the necessary database backend installed for connection string you're trying to use. Available backends include:

Postgresql:	pip install psycopg2
MySQL:		pip install mysql-connector-python

For details on connection strings and other backends, please see the SQLAlchemy documentation on dialects at: 

http://www.sqlalchemy.org/docs/dialects/


```

**Comment by mstralka** [comment]
@sido420 I dug through the SQLAlchemy documentation and read this warning for the mysql-connector-python:
https://docs.sqlalchemy.org/en/14/dialects/mysql.html#module-sqlalchemy.dialects.mysql.mysqlconnector
![image](https://user-images.githubusercontent.com/439680/110046513-2c40d480-7d1a-11eb-9728-0993f807baa5.png)

So I switched to the [mysqldb](https://docs.sqlalchemy.org/en/14/dialects/mysql.html#module-sqlalchemy.dialects.mysql.mysqldb) module [homepage](https://pypi.org/project/mysqlclient/) client and installed it like this on Ubuntu 20.04 with python 3:
~~~
sudo apt install python3-dev default-libmysqlclient-dev build-essential
pip3 install csvkit
pip3 install mysqlclient
~~~

Then I changed my connection string like this:
~~~
mysql+mysqldb://user:pass@host/database
~~~

That made csvsql work.
Hope that helps

**Comment by jpmckinney** [comment]
I've made a commit to mention mysqlclient in addition to mysql-connector-python

**Comment by gmuc** [comment]
"Hope that helps" > it helps perfect, the usage of pip3 is the point (not pip!!!)
