### ISSUE TITLE
PIP install fails with "Package icu-i18n was not found in the pkg-config search path"

### ISSUE THREAD

**Issue by LeadManPL** [wireservice/csvkit#1116]
On recent CentOS Linux release 7.9.2009 (Core)  installation via PIP fails with following info. As a result csvkit is not installed. 
csvkit is uavailable in official Centos repo.
Any hints how to workaround?

```
# pip3.6 install csvkit --proxy http://1.2.3.4:80/
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3.6 install --user` instead.
Collecting csvkit
  Downloading https://files.pythonhosted.org/packages/95/c9/8dd118c0ea0114125a8bf50d552626b95f6478bcf29a252296e93d778855/csvkit-1.0.5.tar.gz (3.8MB)
    100% |████████████████████████████████| 3.8MB 304kB/s 
Collecting agate>=1.6.1 (from csvkit)
  Downloading https://files.pythonhosted.org/packages/da/ec/73bf438732d6e38b380fab9e4dcdfa2b227a984e50c3b56cc9a128fbae9b/agate-1.6.2.tar.gz (191kB)
    100% |████████████████████████████████| 194kB 1.1MB/s 
Collecting agate-excel>=0.2.2 (from csvkit)
  Downloading https://files.pythonhosted.org/packages/a9/cd/ba7ce638900a91f00e6ebaa72c46fc90bfc13cb595071cee82c96057d5d6/agate-excel-0.2.3.tar.gz (153kB)
    100% |████████████████████████████████| 163kB 748kB/s 
Collecting agate-dbf>=0.2.0 (from csvkit)
  Downloading https://files.pythonhosted.org/packages/54/70/a32dfaa47cb7b4e4d70aff67d89c32984085b946442d26a9d9fca7d96d8b/agate-dbf-0.2.2.tar.gz
Collecting agate-sql>=0.5.3 (from csvkit)
  Downloading https://files.pythonhosted.org/packages/f2/97/261281b84bbb35502d29e39da2f1f0ee3d5d08bd982e48fcb8294b69a0e7/agate-sql-0.5.6.tar.gz
Requirement already satisfied: six>=1.6.1 in /usr/local/lib/python3.6/site-packages (from csvkit)
Collecting pytimeparse>=1.1.5 (from agate>=1.6.1->csvkit)
  Downloading https://files.pythonhosted.org/packages/1b/b4/afd75551a3b910abd1d922dbd45e49e5deeb4d47dc50209ce489ba9844dd/pytimeparse-1.1.8-py2.py3-none-any.whl
Collecting parsedatetime>=2.1 (from agate>=1.6.1->csvkit)
  Downloading https://files.pythonhosted.org/packages/9d/a4/3dd804926a42537bf69fb3ebb9fd72a50ba84f807d95df5ae016606c976c/parsedatetime-2.6-py3-none-any.whl (42kB)
    100% |████████████████████████████████| 51kB 999kB/s 
Collecting Babel>=2.0 (from agate>=1.6.1->csvkit)
  Downloading https://files.pythonhosted.org/packages/dd/a5/81076e10b5ef74493cf08a8e419e61b64324c9c55db4aa7f89c0240c4873/Babel-2.9.0-py2.py3-none-any.whl (8.8MB)
    100% |████████████████████████████████| 8.8MB 176kB/s 
Collecting isodate>=0.5.4 (from agate>=1.6.1->csvkit)
  Downloading https://files.pythonhosted.org/packages/9b/9f/b36f7774ff5ea8e428fdcfc4bb332c39ee5b9362ddd3d40d9516a55221b2/isodate-0.6.0-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 51kB 1.5MB/s 
Collecting python-slugify>=1.2.1 (from agate>=1.6.1->csvkit)
  Downloading https://files.pythonhosted.org/packages/9f/42/e336f96a8b6007428df772d0d159b8eee9b2f1811593a4931150660402c0/python-slugify-4.0.1.tar.gz
Collecting leather>=0.3.2 (from agate>=1.6.1->csvkit)
  Downloading https://files.pythonhosted.org/packages/45/f4/692a53df6708caca1c6d088c6d9003940f164f98bd9df2bdc86233641e9c/leather-0.3.3-py3-none-any.whl
Collecting PyICU>=2.4.2 (from agate>=1.6.1->csvkit)
  Downloading https://files.pythonhosted.org/packages/76/5d/6318f86c81665ddccc4a14408525297aec0c73a71a14994a3cbf822aef2a/PyICU-2.7.1.tar.gz (189kB)
    100% |████████████████████████████████| 194kB 1.1MB/s 
    Complete output from command python setup.py egg_info:
    Package icu-i18n was not found in the pkg-config search path.
    Perhaps you should add the directory containing `icu-i18n.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'icu-i18n' found
    (running 'icu-config --version')
    (running 'pkg-config --modversion icu-i18n')
    Traceback (most recent call last):
      File "/tmp/pip-build-cth80kky/PyICU/setup.py", line 63, in <module>
        ICU_VERSION = os.environ['ICU_VERSION']
      File "/usr/lib64/python3.6/os.py", line 669, in __getitem__
        raise KeyError(key) from None
    KeyError: 'ICU_VERSION'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-build-cth80kky/PyICU/setup.py", line 66, in <module>
        ICU_VERSION = check_output(('icu-config', '--version')).strip()
      File "/tmp/pip-build-cth80kky/PyICU/setup.py", line 19, in check_output
        return subprocess_check_output(popenargs)
      File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "/usr/lib64/python3.6/subprocess.py", line 423, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
        restore_signals, start_new_session)
      File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'icu-config': 'icu-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-build-cth80kky/PyICU/setup.py", line 69, in <module>
        ICU_VERSION = check_output(('pkg-config', '--modversion', 'icu-i18n')).strip()
      File "/tmp/pip-build-cth80kky/PyICU/setup.py", line 19, in check_output
        return subprocess_check_output(popenargs)
      File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "/usr/lib64/python3.6/subprocess.py", line 438, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '('pkg-config', '--modversion', 'icu-i18n')' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-cth80kky/PyICU/setup.py", line 74, in <module>
        ''')
    RuntimeError:
    Please install pkg-config on your system or set the ICU_VERSION environment
    variable to the version of ICU you have installed.
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cth80kky/PyICU/

```

**Comment by anthonydb** [comment]
Related to https://github.com/wireservice/agate/issues/755 and https://github.com/wireservice/agate/issues/754, I believe.

**Comment by LeadManPL** [comment]
I managed to do
```
# pip3.6 install --upgrade pip --proxy https://10.251.224.100:80/
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3.6 install --user` instead.
Collecting pip
  Downloading https://files.pythonhosted.org/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 581kB/s 
Installing collected packages: pip
Successfully installed pip-21.0.1

```

and then was able to install csvkit. It gave me a lot of arrors, but binaries are now visible in PATH

**Comment by jpmckinney** [comment]
Related #1127

**Comment by mikez** [comment]
I just experienced the same error. Setting the `PATH` explicitly as outlined [here](https://github.com/googlefonts/pyfontaine/issues/109#issuecomment-604872347) resolved it for me.

**Comment by Christopher-Hayes** [comment]
This worked for me (Ubuntu): https://github.com/ovalhub/pyicu/issues/141#issuecomment-797770861
```
sudo apt install libicu-dev
pip install --upgrade pip setuptools
```
