### ISSUE TITLE
Problem installing on debian 10

### ISSUE THREAD

**Issue by realtebo** [wireservice/csvkit#1122]
```
 pip install csvkit
Collecting csvkit
  Downloading https://files.pythonhosted.org/packages/95/c9/8dd118c0ea0114125a8bf50d552626b95f6478bcf29a252296e93d778855/csvkit-1.0.5.tar.gz (3.8MB)
    100% |████████████████████████████████| 3.8MB 312kB/s
Collecting agate-dbf>=0.2.0 (from csvkit)
  Downloading https://files.pythonhosted.org/packages/54/70/a32dfaa47cb7b4e4d70aff67d89c32984085b946442d26a9d9fca7d96d8b/agate-dbf-0.2.2.tar.gz
Collecting agate-excel>=0.2.2 (from csvkit)
  Downloading https://files.pythonhosted.org/packages/a9/cd/ba7ce638900a91f00e6ebaa72c46fc90bfc13cb595071cee82c96057d5d6/agate-excel-0.2.3.tar.gz (153kB)
    100% |████████████████████████████████| 163kB 6.1MB/s
Collecting agate-sql>=0.5.3 (from csvkit)
  Downloading https://files.pythonhosted.org/packages/f2/97/261281b84bbb35502d29e39da2f1f0ee3d5d08bd982e48fcb8294b69a0e7/agate-sql-0.5.6.tar.gz
Collecting agate>=1.6.1 (from csvkit)
  Downloading https://files.pythonhosted.org/packages/da/ec/73bf438732d6e38b380fab9e4dcdfa2b227a984e50c3b56cc9a128fbae9b/agate-1.6.2.tar.gz (191kB)
    100% |████████████████████████████████| 194kB 4.9MB/s
Requirement already satisfied: six>=1.6.1 in /usr/lib/python2.7/dist-packages (from csvkit) (1.12.0)
Collecting dbfread>=2.0.5 (from agate-dbf>=0.2.0->csvkit)
  Downloading https://files.pythonhosted.org/packages/4c/94/51349e43503e30ed7b4ecfe68a8809cdb58f722c0feb79d18b1f1e36fe74/dbfread-2.0.7-py2.py3-none-any.whl
Collecting openpyxl>=2.3.0 (from agate-excel>=0.2.2->csvkit)
  Downloading https://files.pythonhosted.org/packages/d6/26/eb28e975b7a37aad38d7ec4f7a0f652bdee6ecf36e6bd06f473c5af9b87b/openpyxl-2.6.4.tar.gz (173kB)
    100% |████████████████████████████████| 174kB 6.1MB/s
Collecting xlrd>=0.9.4 (from agate-excel>=0.2.2->csvkit)
  Downloading https://files.pythonhosted.org/packages/a6/0c/c2a72d51fe56e08a08acc85d13013558a2d793028ae7385448a6ccdfae64/xlrd-2.0.1-py2.py3-none-any.whl (96kB)
    100% |████████████████████████████████| 102kB 8.3MB/s
Collecting sqlalchemy>=1.0.8 (from agate-sql>=0.5.3->csvkit)
  Downloading https://files.pythonhosted.org/packages/7a/96/98b88d3fdc8637239c4dfa82715ad7511491e1df5fb1021f61ecc3216e54/SQLAlchemy-1.4.14-cp27-cp27mu-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 800kB/s
Collecting Babel>=2.0 (from agate>=1.6.1->csvkit)
  Downloading https://files.pythonhosted.org/packages/aa/96/4ba93c5f40459dc850d25f9ba93f869a623e77aaecc7a9344e19c01942cf/Babel-2.9.1-py2.py3-none-any.whl (8.8MB)
    100% |████████████████████████████████| 8.8MB 142kB/s
Collecting PyICU>=2.4.2 (from agate>=1.6.1->csvkit)
  Downloading https://files.pythonhosted.org/packages/50/62/230bb78141a03cb3849a1f8ab390eed290a9430b3dabb496c51228271e0b/PyICU-2.7.3.tar.gz (295kB)
    100% |████████████████████████████████| 296kB 2.3MB/s
    Complete output from command python setup.py egg_info:
    Package icu-i18n was not found in the pkg-config search path.
    Perhaps you should add the directory containing `icu-i18n.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'icu-i18n' found
    (running 'icu-config --version')
    (running 'pkg-config --modversion icu-i18n')
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rksJUd/PyICU/setup.py", line 74, in <module>
        ''')
    RuntimeError:
    Please install pkg-config on your system or set the ICU_VERSION environment
    variable to the version of ICU you have installed.

```

**Comment by realtebo** [comment]
Please note that pkg-config is ALREADY installed inb the system.
Probably there is a missing dependency declaration

**Comment by jpmckinney** [comment]
Do you have `python3-icu`?

```
apt-get install python3-icu
```

**Comment by jpmckinney** [comment]
Or, you might need to upgrade `pip`: https://github.com/wireservice/csvkit/issues/1116#issuecomment-818582797

**Comment by jpmckinney** [comment]
Related: #1127
