### ISSUE TITLE
StopIteration error

### ISSUE THREAD

**Issue by saleyn** [wireservice/csvkit#1124]
This doesn't seem right that csvcut produces an exception and outputs `StopIteration` when it receives no data on stdin:
```
$ cat /dev/null | csvcut -v -c a
Traceback (most recent call last):
  File "/usr/bin/csvcut", line 33, in <module>
    sys.exit(load_entry_point('csvkit==1.0.5', 'console_scripts', 'csvcut')())
  File "/usr/lib/python3.9/site-packages/csvkit/utilities/csvcut.py", line 55, in launch_new_instance
    utility.run()
  File "/usr/lib/python3.9/site-packages/csvkit/cli.py", line 118, in run
    self.main()
  File "/usr/lib/python3.9/site-packages/csvkit/utilities/csvcut.py", line 41, in main
    rows, column_names, column_ids = self.get_rows_and_column_names_and_column_ids(**self.reader_kwargs)
  File "/usr/lib/python3.9/site-packages/csvkit/cli.py", line 346, in get_rows_and_column_names_and_column_ids
    column_names = next(rows)
  File "/usr/lib/python3.9/site-packages/agate/csv_py3.py", line 34, in __next__
    row = next(self.reader)
StopIteration
```

**Comment by jpmckinney** [comment]
What is a realistic scenario in which this would occur? We test for `echo "" | csvcut`, but we don't currently test for stdin with no data at all.

**Comment by saleyn** [comment]
The realistic scenario is when the head of the pipe for some reason generates empty data set (due to an error).  In that case the expected output from csvcut would be to just exit silently, so that its semantic doesn't change the output of `cat /dev/null`.

**Comment by jpmckinney** [comment]
I've fixed this for at least csvcut and csvgrep. Thanks for reporting!
