### ISSUE TITLE
Encoding error on Win10 UTF8 file

### ISSUE THREAD

**Issue by techhobbit** [wireservice/csvkit#1158]
There is one other report about encoding errors on Win10, but this may be different. Including more info:

Using Powershell I'm retrieving data from a site using curl.exe and saving as a UTF-16 file, which fails csv2kit conversion unless I convert to UTF-8. After reencoding with powershell 'set-content', all files succeed in json>csv conversion except this one file, which complains about a newline character. I've tried converting it multiple ways using multiple apps (including notepad, notepad++, etc) and multiple formats (UTF8/ANSI and back) but no joy on this one text file.

Calling from powershell
in2csv.py 1.0.6
Python 3.10.1
Windows 10 Version 10.0.19043.1415

python.exe : Traceback (most recent call last):
At C:\...\Curl.ps1:8 char:3
+   python.exe $script -v -k items $folder$i.json > $folder$i.csv
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "C:\...\AppData\Local\Programs\Python\Python310\Scripts\csvkit-master\csvkit\utilities\in2csv.py", line 207, in 
<module>
    launch_new_instance()
  File "C:\...\AppData\Local\Programs\Python\Python310\Scripts\csvkit-master\csvkit\utilities\in2csv.py", line 203, in 
launch_new_instance
    utility.run()
  File "C:\...\AppData\Local\Programs\Python\Python310\lib\site-packages\csvkit\cli.py", line 118, in run
    self.main()
  File "C:\...\AppData\Local\Programs\Python\Python310\Scripts\csvkit-master\csvkit\utilities\in2csv.py", line 171, in 
main
    table.to_csv(self.output_file, **self.writer_kwargs)
  File "C:\...\AppData\Local\Programs\Python\Python310\lib\site-packages\agate\table\to_csv.py", line 43, in to_csv
    writer.writerow(tuple(csv_funcs[i](d) for i, d in enumerate(row)))
  File "C:\...\AppData\Local\Programs\Python\Python310\lib\site-packages\agate\csv_py3.py", line 92, in writerow
    self.writer.writerow(row)
  File "C:\...\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2028' in position 11113: character maps to <undefined>

**Comment by abneetwats24** [comment]
add -e <your encoding>
for example
```cmd
python.exe $script -v -k items $folder$i.json > $folder$i.csv -e utf-8
```
you can replace utf-8 with your encoding as utf-16 or utf-32 or utf-8-sig(if error with BOM header)

**Comment by techhobbit** [comment]
Thanks. Just tried adding "-e utf-16" for the original utf-16 encoded file, and tried re-encoding as uft-8 and adding "-e utf-8". Still fails either way. Same issue - choking on the line separator - '\u2028 is undefined' error. Output below:

    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "...\Python310\Scripts\csvkit-master\csvkit\utilities\in2csv.py", line 207, in 
<module>
    launch_new_instance()
  File "...\Python310\Scripts\csvkit-master\csvkit\utilities\in2csv.py", line 203, in 
launch_new_instance
    utility.run()
  File "...\Python310\lib\site-packages\csvkit\cli.py", line 118, in run
    self.main()
  File "...\Python310\Scripts\csvkit-master\csvkit\utilities\in2csv.py", line 171, in 
main
    table.to_csv(self.output_file, **self.writer_kwargs)
  File "...\Python310\lib\site-packages\agate\table\to_csv.py", line 43, in to_csv
    writer.writerow(tuple(csv_funcs[i](d) for i, d in enumerate(row)))
  File "...\Python310\lib\site-packages\agate\csv_py3.py", line 92, in writerow
    self.writer.writerow(row)
  File "...\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2028' in position 11113: character maps to <undefined>

**Comment by techhobbit** [comment]
Last of that error message should say "character maps to <undefined>"

**Comment by techhobbit** [comment]
"< undefined >"

**Comment by abneetwats24** [comment]
if you are using windows try with encoding 'latin1', 'iso-8859-1' or 'cp1252'
also, if that doesn't work, set following environment variable

```cmd 
set PYTHONIOENCODING=windows-1252
set PYTHONLEGACYWINDOWSSTDIO=windows-1252
```

**Comment by techhobbit** [comment]
Thanks for the suggestions. Sadly, no improvement.

I tried using all of those encodings, but it only works at all if I use UTF8/UTF-8-SIG/UTF16 (depending on what I've done to attempt to re-encode the file first). I know how I'm encoding the file, which I've attempted in various ways: re-saving with notepad with new encoding, re-encoding with notepad++, using the "get-content | set-content -Encoding" commands in powershell... so on paper I know it is encoded correctly. But it doesn't matter what method I use; same result. Apparently there is some kind of character in these files the script still doesn't like, or some input that it is choking on. I suspect it is a fault in how it accepts the input rather than an actual encoding issue at this point. Some combination of characters it doesn't like.

Those environment variables didn't make a difference.

**Comment by jpmckinney** [comment]
@techhobbit Can you attach the file (or some sample that causes the error)?

**Comment by techhobbit** [comment]
[tickets33.txt](https://github.com/wireservice/csvkit/files/8198659/tickets33.txt)
Heavily redacted so I can post it, but it still throws the error.

**Comment by jpmckinney** [comment]
What happens if you `set PYTHONUTF8=1` and `set PYTHONIOENCODING=utf-8` before running the command?

**Comment by Luuk34** [comment]
```
D:\TEMP>set PYTHONUTF8=1

D:\TEMP>set PYTHONIOENCODING=utf-8

D:\TEMP>in2csv -e utf-16 -f json -k items tickets33.txt  > out2.txt
```

[out2.txt](https://github.com/wireservice/csvkit/files/11753634/out2.txt)
