### ISSUE TITLE
csvsql: Add error/warning if no input provided

### ISSUE THREAD

**Issue by goldman7911** [wireservice/csvkit#1169]
I not getting any feedback from these commands. How could I troubleshoot further what is really happening? 

Tried both 
1 - PS C:\Users\goldman> csvsql -v --db postgresql://xxx:yyyy@172.27.109.128:5432/u2020 --query "SELECT * FROM public.cim_bts;"
2 - PS C:\Users\goldman> csvsql -v --db postgresql+psycopg2://xxx:yyyy@172.27.109.128:5432/u2020 --query "SELECT * FROM public.cim_bts;"

Sending logs after ctrl c pressed

```
PS C:\Users\goldman> csvsql -v --db postgresql://xxx:yyy@172.27.109.128:5432/u2020 --query "SELECT * FROM public.cim_bts;"


Traceback (most recent call last):
  File "C:\Users\goldman\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\goldman\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\goldman\AppData\Local\Programs\Python\Python310\Scripts\csvsql.exe\__main__.py", line 7, in <module>
  File "C:\Users\goldman\AppData\Local\Programs\Python\Python310\lib\site-packages\csvkit\utilities\csvsql.py", line 251, in launch_new_instance
    utility.run()
  File "C:\Users\goldman\AppData\Local\Programs\Python\Python310\lib\site-packages\csvkit\cli.py", line 127, in run
    self.main()
  File "C:\Users\goldman\AppData\Local\Programs\Python\Python310\lib\site-packages\csvkit\utilities\csvsql.py", line 144, in main
    self._failsafe_main()
  File "C:\Users\goldman\AppData\Local\Programs\Python\Python310\lib\site-packages\csvkit\utilities\csvsql.py", line 175, in _failsafe_main
    table = agate.Table.from_csv(
  File "C:\Users\goldman\AppData\Local\Programs\Python\Python310\lib\site-packages\agate\table\from_csv.py", line 69, in from_csv
    contents = six.StringIO(f.read())
KeyboardInterrupt
```

env:
Windows 10 Pro 21H2 19044.1586
minikube version: v1.25.2
PSQL running on top of Docker 20.10.13
Python 3.10.2
```
PS C:\Users\goldman> pip list
Package             Version
------------------- ---------
agate               1.6.3
agate-dbf           0.2.2
agate-excel         0.2.5
agate-sql           0.5.8
Babel               2.9.1
certifi             2021.10.8
charset-normalizer  2.0.12
colorama            0.4.4
csvkit              1.0.7
dbfread             2.0.7
docopt              0.6.2
et-xmlfile          1.1.0
future              0.18.2
greenlet            1.1.2
idna                3.3
isodate             0.6.1
leather             0.3.4
olefile             0.46
openpyxl            3.0.9
parsedatetime       2.4
pip                 22.0.3
pomodoro-calculator 1.0.2
psycopg2            2.9.3
pyreadline3         3.4.1
python-slugify      6.1.1
pytimeparse         1.1.8
pytz                2022.1
requests            2.27.1
setuptools          58.1.0
six                 1.16.0
SQLAlchemy          1.4.35
text-unidecode      1.3
urllib3             1.26.8
xlrd                2.0.1
```

**Comment by jpmckinney** [comment]
Ah, so `csvsql` needs either an input file or piped data. What's happening is that it isn't being provided either, and so it's waiting for input. I'll try to add a message/warning/error if nothing is provided.
