### ISSUE TITLE
Encoding ignored when reading from stdin

### ISSUE THREAD

**Issue by frafra** [wireservice/csvkit#1172]
I set `utf-16-le` as encoding, but `utf-8` is used:
```
in2csv -v -f csv -e "utf-16-le" -d ";" < csv 
Traceback (most recent call last):
  File "/home/user/.local/bin/in2csv", line 8, in <module>
    sys.exit(launch_new_instance())
  File "/home/user/.local/pipx/venvs/csvkit/lib/python3.8/site-packages/csvkit/utilities/in2csv.py", line 203, in launch_new_instance
    utility.run()
  File "/home/user/.local/pipx/venvs/csvkit/lib/python3.8/site-packages/csvkit/cli.py", line 127, in run
    self.main()
  File "/home/user/.local/pipx/venvs/csvkit/lib/python3.8/site-packages/csvkit/utilities/in2csv.py", line 157, in main
    table = agate.Table.from_csv(self.input_file, **kwargs)
  File "/home/user/.local/pipx/venvs/csvkit/lib/python3.8/site-packages/agate/table/from_csv.py", line 69, in from_csv
    contents = six.StringIO(f.read())
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 68: invalid continuation byte
```

Workaround: `PYTHONIOENCODING="utf-16-le" in2csv -f csv -d ";" < csv`

Reading the file directly works as well: `in2csv -v -f csv -e "utf-16-le" -d ";" csv`

**Comment by jpmckinney** [comment]
As documented here: https://csvkit.readthedocs.io/en/latest/common_arguments.html

> The --encoding option has no effect if reading from standard input. Set the PYTHONIOENCODING environment variable instead.

The reason is that, when using standard input, we take the encoding from the environment, which is typically UTF-8. `-e` is for file encoding, not environment encoding.
