### ISSUE TITLE
Import errors using Python 3.7.3

### ISSUE THREAD

**Issue by DaveJarvis** [wireservice/csvkit#1207]
``` bash
$ python --version
Python 3.7.3
$ sudo apt install python-pip
$ sudo pip install csvkit
$ in2csv infer-out/report.json 
Traceback (most recent call last):
  File "/usr/local/bin/in2csv", line 6, in <module>
    from csvkit.utilities.in2csv import launch_new_instance
  File "/usr/local/lib/python2.7/dist-packages/csvkit/__init__.py", line 15, in <module>
    import agate
  File "/usr/local/lib/python2.7/dist-packages/agate/__init__.py", line 5, in <module>
    from agate.aggregations import *
  File "/usr/local/lib/python2.7/dist-packages/agate/aggregations/__init__.py", line 21, in <module>
    from agate.aggregations.count import Count
  File "/usr/local/lib/python2.7/dist-packages/agate/aggregations/count.py", line 5, in <module>
    from agate.utils import default
  File "/usr/local/lib/python2.7/dist-packages/agate/utils.py", line 12, in <module>
    from collections.abc import Sequence
ImportError: No module named abc
```

**Comment by jpmckinney** [comment]
As you can see from the traceback, you are running python2.7.

You probably wanted to do `apt install python3-pip`.

Since you will have two pip's, you probably also want to run `pip3 install csvkit`.
