### ISSUE TITLE
in2csv throws `unsupported operand type(s) for +=: 'float' and 'str'` for this xls 

### ISSUE THREAD

**Issue by fgregg** [wireservice/csvkit#611]
This file can't be converted by `in2csv` https://drive.google.com/open?id=0B5tDdMTTIKEnODBSWElnT3JLeFE

It throws the following errors.

```bash
in2csv -v RC97_layout.xls Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/csvkit/table.py", line 121, in _deduplicate_column_name
    i = column.name.rindex('_')
AttributeError: 'float' object has no attribute 'rindex'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/in2csv", line 11, in <module>
    sys.exit(launch_new_instance())
  File "/usr/local/lib/python3.4/dist-packages/csvkit/utilities/in2csv.py", line 82, in launch_new_instance
    utility.main()
  File "/usr/local/lib/python3.4/dist-packages/csvkit/utilities/in2csv.py", line 76, in main
    data = convert.convert(self.input_file, filetype, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/csvkit/convert/__init__.py", line 37, in convert
    return xls2csv(f, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/csvkit/convert/xls.py", line 147, in xls2csv
    tab.append(column)
  File "/usr/local/lib/python3.4/dist-packages/csvkit/table.py", line 131, in append
    self._deduplicate_column_name(column)
  File "/usr/local/lib/python3.4/dist-packages/csvkit/table.py", line 125, in _deduplicate_column_name
    column.name += '_2'
TypeError: unsupported operand type(s) for +=: 'float' and 'str'


```

**Comment by jpmckinney** [comment]
Using the GitHub version, the output is:

```
/Users/james/.virtualenvs/csvkit/src/agate/agate/table/__init__.py:89: RuntimeWarning: Column name not specified. "a" will be used as name.
  warnings.warn('Column name not specified. "%s" will be used as name.' % new_column_name, RuntimeWarning)
/Users/james/.virtualenvs/csvkit/src/agate/agate/table/__init__.py:89: RuntimeWarning: Column name not specified. "b" will be used as name.
  warnings.warn('Column name not specified. "%s" will be used as name.' % new_column_name, RuntimeWarning)
/Users/james/.virtualenvs/csvkit/src/agate/agate/table/__init__.py:89: RuntimeWarning: Column name not specified. "c" will be used as name.
  warnings.warn('Column name not specified. "%s" will be used as name.' % new_column_name, RuntimeWarning)
Column names must be strings or None.
```

**Comment by jpmckinney** [comment]
Fixed if using the GitHub version of agate-excel.
