### ISSUE TITLE
Cannot read xlsx files

### ISSUE THREAD

**Issue by aabadi** [wireservice/csvkit#651]
Im trying to convert an xlsx into csv, but Im not being able. I found that the xlsx file has been created using http://www.spreadsheetgear.com/.

Do you know if there is a solution for those type of files?
(attached you will find the file)

[aa.xlsx](https://github.com/wireservice/csvkit/files/425355/aa.xlsx)

**Comment by jpmckinney** [comment]
What is the error message? (Run the command with `-v` to get more verbose output). What is your version of csvkit? Find out with `pip freeze | grep csvkit`

**Comment by aabadi** [comment]
**csvkit version:**
You are using pip version 7.1.0, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
csvkit==0.9.1


**Error (with -v)**
/usr/lib/python2.7/site-packages/openpyxl/workbook/names/named_range.py:121: UserWarning: Discarded range with reserved name
  warnings.warn("Discarded range with reserved name")
Traceback (most recent call last):
  File "/bin/in2csv", line 9, in <module>
    load_entry_point('csvkit==0.9.1', 'console_scripts', 'in2csv')()
  File "/usr/lib/python2.7/site-packages/csvkit/utilities/in2csv.py", line 82, in launch_new_instance
    utility.main()
  File "/usr/lib/python2.7/site-packages/csvkit/utilities/in2csv.py", line 76, in main
    data = convert.convert(self.input_file, filetype, **kwargs)
  File "/usr/lib/python2.7/site-packages/csvkit/convert/__init__.py", line 39, in convert
    return xlsx2csv(f, **kwargs)
  File "/usr/lib/python2.7/site-packages/csvkit/convert/xlsx.py", line 58, in xlsx2csv
    for i, row in enumerate(sheet.iter_rows()):
  File "/usr/lib/python2.7/site-packages/openpyxl/worksheet/iter_worksheet.py", line 105, in get_squared_range
    row_id = int(element.get("r"))
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by jpmckinney** [comment]
Can you try with the latest version from GitHub?

    pip install -e git+git://github.com/onyxfish/csvkit.git@master#egg=csvkit

**Comment by aabadi** [comment]
Failed again :(

/usr/lib/python2.7/site-packages/openpyxl/workbook/names/named_range.py:125: UserWarning: Discarded range with reserved name
  warnings.warn("Discarded range with reserved name")
Traceback (most recent call last):
  File "/bin/in2csv", line 9, in <module>
    load_entry_point('csvkit', 'console_scripts', 'in2csv')()
  File "/home/aabadi/TEST_MAIL/src/csvkit/csvkit/utilities/in2csv.py", line 115, in launch_new_instance
    utility.main()
  File "/home/aabadi/TEST_MAIL/src/csvkit/csvkit/utilities/in2csv.py", line 105, in main
    table = agate.Table.from_xlsx(self.input_file, sheet=kwargs.get('sheet'))
  File "/usr/lib/python2.7/site-packages/agateexcel/table_xlsx.py", line 44, in from_xlsx
    for i, row in enumerate(sheet.rows):
  File "/usr/lib/python2.7/site-packages/openpyxl/worksheet/read_only.py", line 114, in get_squared_range
    row_id = int(element.get("r"))
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by jpmckinney** [comment]
It's a bug in openpyxl. If you `pip install --upgrade openpyxl==2.4.0b1` it works.
