### ISSUE TITLE
Option --write-all-sheets is available?

### ISSUE THREAD

**Issue by aabadi** [wireservice/csvkit#654]
Hi!
I would like to know if adding the option **--write-all-sheets** works or for the moment is NOT working.
As of today in2csv is raising an error "in2csv: error: unrecognized arguments: --write-all-sheets"

Im using the latest version from GitHub (pip install -e git+git://github.com/onyxfish/csvkit.git@master#egg=csvkit)

Am I doing something wrong ?

Thks in advance

**Comment by jpmckinney** [comment]
The pull request is still open. The feature hasn't been merged yet. There were some changes in how Excel was handled (the functionality moved out into the agate-excel package), so we need to update the pull request to get this feature implemented.

**Comment by raveslave** [comment]
Tested the all sheets argument on 1.0.2, getting an error

```
 --write-sheets WRITE_SHEETS
                        The names of the Excel sheets to write to files, or
                        "-" to write all sheets.

i.e.
in2csv filewithmanysheets.xls --write-sheets "-"
```

```
Traceback (most recent call last):
  File "/usr/local/bin/in2csv", line 11, in <module>
    sys.exit(launch_new_instance())
  File "/usr/local/lib/python2.7/site-packages/csvkit/utilities/in2csv.py", line 180, in launch_new_instance
    utility.run()
  File "/usr/local/lib/python2.7/site-packages/csvkit/cli.py", line 114, in run
    self.main()
  File "/usr/local/lib/python2.7/site-packages/csvkit/utilities/in2csv.py", line 163, in main
    tables = agate.Table.from_xls(self.input_file, sheet=sheets, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/agateexcel/table_xls.py", line 30, in from_xls
    book = xlrd.open_workbook(file_contents=path.read())
  File "/usr/local/lib/python2.7/site-packages/xlrd/__init__.py", line 116, in open_workbook
    with open(filename, "rb") as f:
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

Testing with --names on the same file works fine and outputs 13 sheet names, no blanks no unicode.

**Comment by jpmckinney** [comment]
@raveslave Can you open a new issue?

**Comment by raveslave** [comment]
see #887
