### ISSUE TITLE
agate: problem with slugify, 'module' object has no attribute 'VERSION1'

### ISSUE THREAD

**Issue by Tabea-K** [wireservice/csvkit#677]
Hi there,

csvkit was running fine on my computer, until I recently got this error message:

```bash
Traceback (most recent call last):
  File "/usr/local/bin/csvlook", line 9, in <module>
    load_entry_point('csvkit==1.0.0', 'console_scripts', 'csvlook')()
  File "/usr/local/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 343, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2307, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2013, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/site-packages/csvkit-1.0.0-py2.7.egg/csvkit/__init__.py", line 15, in <module>
    import agate
  File "/usr/local/lib/python2.7/site-packages/agate-1.4.0-py2.7.egg/agate/__init__.py", line 5, in <module>
    from agate.aggregations import *
  File "/usr/local/lib/python2.7/site-packages/agate-1.4.0-py2.7.egg/agate/aggregations/__init__.py", line 22, in <module>
    from agate.aggregations.count import Count  # noqa
  File "/usr/local/lib/python2.7/site-packages/agate-1.4.0-py2.7.egg/agate/aggregations/count.py", line 5, in <module>
    from agate.utils import default
  File "/usr/local/lib/python2.7/site-packages/agate-1.4.0-py2.7.egg/agate/utils.py", line 13, in <module>
    from slugify import Slugify, UniqueSlugify
  File "/usr/local/lib/python2.7/site-packages/awesome_slugify-1.6.5-py2.7.egg/slugify/__init__.py", line 2, in <module>
    from slugify.main import Slugify, UniqueSlugify
  File "/usr/local/lib/python2.7/site-packages/awesome_slugify-1.6.5-py2.7.egg/slugify/main.py", line 68, in <module>
    class Slugify(object):
  File "/usr/local/lib/python2.7/site-packages/awesome_slugify-1.6.5-py2.7.egg/slugify/main.py", line 69, in Slugify
    upper_to_upper_letters_re = re.compile(UPPER_TO_UPPER_LETTERS_RE, re.VERBOSE | re.VERSION1)
AttributeError: 'module' object has no attribute 'VERSION1'
```

I tried uninstalling and reinstalling cvskit via pip, but it didn't help.

I also downloaded the repository and ran the csvlook.py script directly from there, which gave me a similar error message.

Does anyone of you have an idea how I could fix this?

Thank you!

**Comment by jpmckinney** [comment]
The bug seems to be in the awesome-slugify and/or regex modules. @nbedi @onyxfish ?

**Comment by onyxfish** [comment]
@Tabea-K Would you mind trying this with the latest release (`1.0.0`). I suspect it's fixed. If not could you let me know what version of python your running and paste in the output of ```pip freeze```? Thanks!

**Comment by jpmckinney** [comment]
It's Python 2.7.

**Comment by onyxfish** [comment]
We're going to be swapping out awesome-slugify [in the next release](https://github.com/wireservice/agate/issues/660) so let's do that before investing any time debugging this.

**Comment by jpmckinney** [comment]
Closed by https://github.com/wireservice/agate/issues/660
