### ISSUE TITLE
pip installation of csvkit fails with UnicodeDecodeError

### ISSUE THREAD

**Issue by epogrebnyak** [wireservice/csvkit#679]
At some point my installation of csvkit (```pip install csvkit```) fails with message below. 
```
  Found existing installation: python-dateutil 2.5.0
Exception:
Traceback (most recent call last):
  File "C:\Users\Евгений\Anaconda3\lib\site-packages\pip\basecommand.py", line 209, in main
    status = self.run(options, args)
  File "C:\Users\Евгений\Anaconda3\lib\site-packages\pip\commands\install.py", line 317, in run
    prefix=options.prefix_path,
  File "C:\Users\Евгений\Anaconda3\lib\site-packages\pip\req\req_set.py", line 726, in install
    requirement.uninstall(auto_confirm=True)
  File "C:\Users\Евгений\Anaconda3\lib\site-packages\pip\req\req_install.py", line 699, in uninstall
    for path in pip.wheel.uninstallation_paths(dist):
  File "C:\Users\Евгений\Anaconda3\lib\site-packages\pip\wheel.py", line 533, in unique
    for item in fn(*args, **kw):
  File "C:\Users\Евгений\Anaconda3\lib\site-packages\pip\wheel.py", line 552, in uninstallation_paths
    r = csv.reader(FakeFile(dist.get_metadata_lines('RECORD')))
  File "C:\Users\Евгений\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1624, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "C:\Users\Евгений\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1621, in get_metadata
    return self._get(self._fn(self.egg_info, name)).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 1615: invalid continuation byte
```

**Comment by jpmckinney** [comment]
It looks like you're on Windows - which version?

Also, which version of python are you running?

**Comment by epogrebnyak** [comment]
Windows 10 and python 3, Anaconda build. I'm suspicious in requirements-py3.txt python-dateutils version is fixed at 2.2, latest is 2.6, maybe that's causing some trouble. Can also try installing with conda manager or running github version to see any difference.

**Comment by epogrebnyak** [comment]
Istallation successful with conda, but fials with pip.

**Comment by JanisE** [comment]
I have a similar problem (Linux Mint 17):

```
$ pip install csvkit
Downloading/unpacking csvkit
  Downloading csvkit-1.0.3.tar.gz (3.8MB): 3.8MB downloaded
  Running setup.py (path:/tmp/pip_build_janis/csvkit/setup.py) egg_info for package csvkit
    
Downloading/unpacking agate>=1.6.1 (from csvkit)
  Downloading agate-1.6.1-py2.py3-none-any.whl (98kB): 98kB downloaded
Downloading/unpacking agate-excel>=0.2.2 (from csvkit)
  Downloading agate-excel-0.2.2.tar.gz
  Running setup.py (path:/tmp/pip_build_janis/agate-excel/setup.py) egg_info for package agate-excel
    
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1235, in prepare_files
    req_to_install.assert_source_matches_version()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 465, in assert_source_matches_version
    % (display_path(self.source_dir), version, self))
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 70, in display_path
    if path.startswith(os.getcwd() + os.path.sep):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 37: ordinal not in range(128)

Storing debug log for failure in /home/janis/.pip/pip.log
```

Probably related to using a non-English locale (lv_LV).

**Comment by jpmckinney** [comment]
@JanisE If you have the option to install Python 3 and then install csvkit, it should work. Python 2.7 has worse unicode support.

**Comment by JanisE** [comment]
OK, thanks for the tip!
