### ISSUE TITLE
I/O Errors when tests fail

### ISSUE THREAD

**Issue by onyxfish** [wireservice/csvkit#699]
Happens anytime another test fails, I have to comment on the basic `launch_new_instance` test, debug the failing test, and then uncomment it.

**Comment by onyxfish** [comment]
The same thing is happening with `test_empty`. I'm having to comment both out.

**Comment by onyxfish** [comment]
This is turning out to be quite the bugbear. It isn't an issue with patch. Once I disabled csvkit's exception handler and traced down in the code I found it's failing when calling `engine.connect()` for sqlalchemy. However, the resulting error is actually in nose, which seems to indicate the problem has something to do with munging stdin/stdout. 

```
Traceback (most recent call last):
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/nose/case.py", line 134, in run
    self.runTest(result)
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/nose/case.py", line 152, in runTest
    test(result)
  File "/Users/cgroskopf/.pyenv/versions/3.5.0/lib/python3.5/unittest/case.py", line 645, in __call__
    return self.run(*args, **kwds)
  File "/Users/cgroskopf/.pyenv/versions/3.5.0/lib/python3.5/unittest/case.py", line 605, in run
    self._feedErrorsToResult(result, outcome.errors)
  File "/Users/cgroskopf/.pyenv/versions/3.5.0/lib/python3.5/unittest/case.py", line 538, in _feedErrorsToResult
    result.addError(test, exc_info)
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/nose/proxy.py", line 128, in addError
    formatted = plugins.formatError(self.test, err)
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/nose/plugins/manager.py", line 141, in chain
    result = meth(*arg, **kw)
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/nose/plugins/capture.py", line 74, in formatError
    test.capturedOutput = output = self.buffer
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/nose/plugins/capture.py", line 112, in _get_buffer
    return self._buf.getvalue()
ValueError: I/O operation on closed file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cgroskopf/.virtualenvs/csvkit/bin/nosetests", line 11, in <module>
    sys.exit(run_exit())
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/Users/cgroskopf/.pyenv/versions/3.5.0/lib/python3.5/unittest/main.py", line 94, in __init__
    self.runTests()
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/nose/core.py", line 62, in run
    test(result)
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/nose/suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/nose/suite.py", line 225, in run
    test(orig)
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/nose/suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/nose/suite.py", line 225, in run
    test(orig)
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/nose/case.py", line 46, in __call__
    return self.run(*arg, **kwarg)
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/nose/case.py", line 139, in run
    result.addError(self, err)
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/nose/proxy.py", line 128, in addError
    formatted = plugins.formatError(self.test, err)
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/nose/plugins/manager.py", line 141, in chain
    result = meth(*arg, **kw)
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/nose/plugins/capture.py", line 74, in formatError
    test.capturedOutput = output = self.buffer
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/nose/plugins/capture.py", line 112, in _get_buffer
    return self._buf.getvalue()
ValueError: I/O operation on closed file
```

Unfortunately it seems I've also got some problems with my psql setup which is making ruling out issues on that side difficult.

**Comment by onyxfish** [comment]
It's the bloody print statements. Inserting a `print` in `TestSQL2CSV.test_launch_new_instance` causes the I/O error.

**Comment by onyxfish** [comment]
Eureka! Utils default to writing their output to standard out and then the `run` wrapper closes it, which means its closed when nose tries to write to it.

**Comment by onyxfish** [comment]
This is now fixed, pending merge.
