### ISSUE TITLE
Error when piping csvcut to csvstat

### ISSUE THREAD

**Issue by onyxfish** [wireservice/csvkit#707]
```
Traceback (most recent call last):
  File "/Users/cgroskopf/.virtualenvs/test/bin/csvstat", line 11, in <module>
    load_entry_point('csvkit', 'console_scripts', 'csvstat')()
  File "/Users/cgroskopf/src/csvkit/csvkit/utilities/csvstat.py", line 183, in launch_new_instance
    utility.run()
  File "/Users/cgroskopf/src/csvkit/csvkit/cli.py", line 118, in run
    self.main()
  File "/Users/cgroskopf/src/csvkit/csvkit/utilities/csvstat.py", line 95, in main
    **self.reader_kwargs
  File "/Users/cgroskopf/.virtualenvs/test/lib/python3.6/site-packages/agate-1.5.2-py3.6.egg/agate/table/from_csv.py", line 65, in from_csv
io.UnsupportedOperation: underlying stream is not seekable
```

**Comment by onyxfish** [comment]
The use of `seek` in agate's `Table.from_csv is breaking pipeability. Choices: buffer the file (maybe not a problem since `from_csv` is certainly going to read all the data anyway?) or build a fancy chain-reader thing that will prepend the sniff sample to the remaining file contents.

**Comment by onyxfish** [comment]
Fixed upon minor agate release.

**Comment by onyxfish** [comment]
Resolve with merge of `agate-join` branch.
