### ISSUE TITLE
in2csv: Github issues example no longer works

### ISSUE THREAD

**Issue by onyxfish** [wireservice/csvkit#724]
I bet the API format changed...

```
curl https://api.github.com/repos/wireservice/csvkit/issues\?state\=open | in2csv -f json -v

Traceback (most recent call last):
  File "/Users/cgroskopf/.virtualenvs/test/bin/in2csv", line 11, in <module>
    load_entry_point('csvkit', 'console_scripts', 'in2csv')()
  File "/Users/cgroskopf/src/csvkit/csvkit/utilities/in2csv.py", line 117, in launch_new_instance
    utility.run()
  File "/Users/cgroskopf/src/csvkit/csvkit/cli.py", line 118, in run
    self.main()
  File "/Users/cgroskopf/src/csvkit/csvkit/utilities/in2csv.py", line 96, in main
    table = agate.Table.from_json(self.input_file, key=self.args.key, **kwargs)
  File "/Users/cgroskopf/src/agate/agate/table/from_json.py", line 61, in from_json
    return Table.from_object(js, row_names=row_names, column_types=column_types)
  File "/Users/cgroskopf/src/agate/agate/table/from_object.py", line 76, in from_object
    return Table(rows, column_names, row_names=row_names, column_types=column_types)
  File "/Users/cgroskopf/src/agate/agate/table/__init__.py", line 132, in __init__
    self._column_types = column_types.run(rows, self._column_names)
  File "/Users/cgroskopf/src/agate/agate/type_tester.py", line 110, in run
    if len(row) > i and not column_type.test(row[i]):
  File "/Users/cgroskopf/src/agate/agate/data_types/base.py", line 29, in test
    self.cast(d)
  File "/Users/cgroskopf/src/agate/agate/data_types/time_delta.py", line 35, in cast
    seconds = pytimeparse.parse(d)
  File "/Users/cgroskopf/.virtualenvs/test/lib/python3.6/site-packages/pytimeparse-1.1.5-py3.6.egg/pytimeparse/timeparse.py", line 147, in timeparse
    sign = -1 if match.groupdict()['sign'] == '-' else 1
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

**Comment by jpmckinney** [comment]
I'm not sure it's an issue with GitHub. I think it's an issue with `agate/data_types/time_delta.py`

**Comment by jpmckinney** [comment]
Marking dupe #736
