### ISSUE TITLE
csvlook: 'NoneType' object has no attribute 'groupdict'

### ISSUE THREAD

**Issue by onyxfish** [wireservice/csvkit#736]
Using test file from #631. Also reported via Twitter by another user.

```
csvcut ~/Downloads/testNonASCII/testNonASCII.csv | csvlook -v

Traceback (most recent call last):
  File "/Users/cgroskopf/.virtualenvs/csvkit/bin/csvlook", line 9, in <module>
    load_entry_point('csvkit==1.0.1', 'console_scripts', 'csvlook')()
  File "/Users/cgroskopf/src/csvkit/csvkit/utilities/csvlook.py", line 44, in launch_new_instance
    utility.run()
  File "/Users/cgroskopf/src/csvkit/csvkit/cli.py", line 113, in run
    self.main()
  File "/Users/cgroskopf/src/csvkit/csvkit/utilities/csvlook.py", line 31, in main
    **self.reader_kwargs
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/agate/table/from_csv.py", line 88, in from_csv
    return Table(rows, column_names, column_types, row_names=row_names)
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/agate/table/__init__.py", line 132, in __init__
    self._column_types = column_types.run(rows, self._column_names)
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/agate/type_tester.py", line 110, in run
    if len(row) > i and not column_type.test(row[i]):
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/agate/data_types/base.py", line 29, in test
    self.cast(d)
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/agate/data_types/time_delta.py", line 35, in cast
    seconds = pytimeparse.parse(d)
  File "/Users/cgroskopf/.virtualenvs/csvkit/lib/python3.5/site-packages/pytimeparse/timeparse.py", line 147, in timeparse
    sign = -1 if match.groupdict()['sign'] == '-' else 1
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

**Comment by onyxfish** [comment]
Tracking upstream.

**Comment by onyxfish** [comment]
Fixed upstream. Need to require next minor agate release for fix.
