### ISSUE TITLE
in2csv: in2csv -v examples/sheets.xls fails

### ISSUE THREAD

**Issue by jpmckinney** [wireservice/csvkit#742]
```
Traceback (most recent call last):
  File "/Users/james/.virtualenvs/csvkit/bin/in2csv", line 9, in <module>
    load_entry_point('csvkit==1.0.2', 'console_scripts', 'in2csv')()
  File "/Users/james/.virtualenvs/csvkit/lib/python3.5/site-packages/csvkit/utilities/in2csv.py", line 133, in launch_new_instance
    utility.run()
  File "/Users/james/.virtualenvs/csvkit/lib/python3.5/site-packages/csvkit/cli.py", line 113, in run
    self.main()
  File "/Users/james/.virtualenvs/csvkit/lib/python3.5/site-packages/csvkit/utilities/in2csv.py", line 116, in main
    table = agate.Table.from_xls(self.input_file, sheet=kwargs.get('sheet'))
  File "/Users/james/.virtualenvs/csvkit/lib/python3.5/site-packages/agateexcel/table_xls.py", line 57, in from_xls
    for i in range(len(columns[0])):
IndexError: list index out of range
```

**Comment by jpmckinney** [comment]
Waiting for upstream merge https://github.com/wireservice/agate-excel/pull/14

**Comment by jpmckinney** [comment]
Merged
