### ISSUE TITLE
Incorrect UnicodeEncodeError

### ISSUE THREAD

**Issue by adamcunnington** [wireservice/csvkit#820]
All details here: https://paste.pound-python.org/show/GIIQyrchxMB2LEWTfpCA/

Sample code, traceback and sample output.

```
all_rows = []
rows = True
while rows:
    result = search_analytics.query(siteUrl=args.site_URL.geturl(), body=params).execute()
    rows = result.get("rows", [])
    item_count = len(rows)
    params["startRow"] += item_count
    if item_count:
        all_rows.extend(rows)
with open(_TEMP_JSON_PATH, "w", encoding="utf-8") as f:
    json.dump(all_rows, f)
os.system("in2csv -e utf-8 -f json \"%s\" > \"%s\"" %(_TEMP_JSON_PATH, _TEMP_CSV_PATH))
os.system("csvcut -e utf-8 \"%s\" -c keys/0,keys/1,keys/2,keys/3,impressions,clicks,position > \"%s\""
          %(_TEMP_CSV_PATH, os.path.join(args.output_file_directory, "SearchConsole_%s_%s.csv" %(args.site_URL.hostname, args.end_date.strftime("%Y%m%d")))))
return
```

in2csv'ing

```
Traceback (most recent call last):
  File "C:\Python Environments\SearchConsoleExtractor\Scripts\in2csv-script.py",
 line 9, in <module>
    load_entry_point('csvkit==1.0.1', 'console_scripts', 'in2csv')()
  File "C:\Python Environments\SearchConsoleExtractor\lib\site-packages\csvkit-1
.0.1-py3.5.egg\csvkit\utilities\in2csv.py", line 117, in launch_new_instance
  File "C:\Python Environments\SearchConsoleExtractor\lib\site-packages\csvkit-1
.0.1-py3.5.egg\csvkit\cli.py", line 113, in run
  File "C:\Python Environments\SearchConsoleExtractor\lib\site-packages\csvkit-1
.0.1-py3.5.egg\csvkit\utilities\in2csv.py", line 107, in main
  File "C:\Python Environments\SearchConsoleExtractor\lib\site-packages\agate-1.
6.0-py3.5.egg\agate\table\to_csv.py", line 43, in to_csv
  File "C:\Python Environments\SearchConsoleExtractor\lib\site-packages\agate-1.
6.0-py3.5.egg\agate\csv_py3.py", line 91, in writerow
  File "C:\Program Files\Python35\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 144-146:
 character maps to <undefined>
```

csvcut'ing

```
Traceback (most recent call last):
  File "C:\Python Environments\SearchConsoleExtractor\Scripts\csvcut-script.py",
 line 9, in <module>
    load_entry_point('csvkit==1.0.1', 'console_scripts', 'csvcut')()
  File "C:\Python Environments\SearchConsoleExtractor\lib\site-packages\csvkit-1
.0.1-py3.5.egg\csvkit\utilities\csvcut.py", line 49, in launch_new_instance
  File "C:\Python Environments\SearchConsoleExtractor\lib\site-packages\csvkit-1
.0.1-py3.5.egg\csvkit\cli.py", line 113, in run
  File "C:\Python Environments\SearchConsoleExtractor\lib\site-packages\csvkit-1
.0.1-py3.5.egg\csvkit\utilities\csvcut.py", line 40, in main
  File "C:\Python Environments\SearchConsoleExtractor\lib\site-packages\agate-1.
6.0-py3.5.egg\agate\csv_py3.py", line 34, in __next__
  File "C:\Python Environments\SearchConsoleExtractor\lib\site-packages\csvkit-1
.0.1-py3.5.egg\csvkit\cli.py", line 55, in __next__
  File "C:\Program Files\Python35\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 7720: inval
id start byte
```

here's the first ~200 characters from the json file

```
[{"impressions": 92278.0, "ctr": 0.5941827954658748, "position": 1.2993996402176033, "keys": ["2017-03-31", "gbr", "http://www.nationwide.co.uk/", "nationwide"], "clicks": 54830.0}, {"impressions":
```

**Comment by jpmckinney** [comment]
Using those 200 characters, I can't reproduce the error. You'll need to share a sample of the JSON data that can actually reproduce the error.

**Comment by jpmckinney** [comment]
Over a month without response, so closing.
