### ISSUE TITLE
Can't convert .xlsx to csv: "File contains no valid workbook part"

### ISSUE THREAD

**Issue by dmccracken123** [wireservice/csvkit#834]
Unfortunately I can't include a copy of the input file, it contains sensitive data. It's downloaded from a property management software program called YARDI Voyager.

This issue only occurs if I haven't opened + saved the workbook yet; if I open it, change nothing, and save it, everything works correctly.

**Command:**
in2csv Check_Register.xlsx -v

**Output:**
Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\in2csv-script.py", line 11, in \<module\>
    load_entry_point('csvkit==1.0.2', 'console_scripts', 'in2csv')()
  File "C:\Program Files\Python36\lib\site-packages\csvkit\utilities\in2csv.py", line 180, in launch_new_instance
    utility.run()
  File "C:\Program Files\Python36\lib\site-packages\csvkit\cli.py", line 114, in run
    self.main()
  File "C:\Program Files\Python36\lib\site-packages\csvkit\utilities\in2csv.py", line 144, in main
    table = agate.Table.from_xlsx(self.input_file, sheet=self.args.sheet, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\agateexcel\table_xlsx.py", line 36, in from_xlsx
    book = openpyxl.load_workbook(f, read_only=True, data_only=True)
  File "C:\Program Files\Python36\lib\site-packages\openpyxl\reader\excel.py", line 171, in load_workbook
    wb_part = _find_workbook_part(package)
  File "C:\Program Files\Python36\lib\site-packages\openpyxl\reader\excel.py", line 131, in _find_workbook_part
    raise IOError("File contains no valid workbook part")
OSError: File contains no valid workbook part

**Python version:**
3.6.1 (64-bit)

**OS version:**
Windows 7 Professional

**Comment by jpmckinney** [comment]
My guess would be that the software produces slightly malformed Excel files that can still be read by Microsoft Excel but can't be read by openpyxl, and then saving the file with Microsoft Excel sets the form that openpyxl expects. Is it a problem to have to open and re-save the file?

**Comment by dmccracken123** [comment]
Yeah it is unfortunately. The reason I'm trying to convert it to csv in the first place is that the file behaves so strangely. Any time it has more than ~10k rows it takes more than 5 minutes just to open the file the first time.

**Comment by jpmckinney** [comment]
What's the output of `pip show openpyxl` ? If the version is greater than 2.4.4, try `pip install openpyxl==2.4.4` and then re-run the above.

This is the relevant issue on openpyxl's repository: https://bitbucket.org/openpyxl/openpyxl/issues/789/unexpected-error-when-loading-a-file which references this pull request: https://bitbucket.org/openpyxl/openpyxl/pull-requests/161/support-workbooks-which-have-a-non/diff

**Comment by dmccracken123** [comment]
Thanks for the help. After downgrading to 2.4.4, I'm getting a different/more descriptive error. Progress!

I downloaded a version of the report with no sensitive data, so I'm attaching it here. The biggest thing I'm seeing in the worksheet's XML file is that it's merging a bunch of cells, which might be causing the mismatch between # of values/# of columns.

**Command**
in2csv Check_Register2.xlsx -v

**Output**
C:\Program Files\Python36\lib\site-packages\agate\utils.py:275: UnnamedColumnWarning: Column 0 has no name. Using "a".
C:\Program Files\Python36\lib\site-packages\agate\utils.py:275: UnnamedColumnWarning: Column 1 has no name. Using "b".
C:\Program Files\Python36\lib\site-packages\agate\utils.py:275: UnnamedColumnWarning: Column 2 has no name. Using "c".
C:\Program Files\Python36\lib\site-packages\agate\utils.py:275: UnnamedColumnWarning: Column 3 has no name. Using "d".
Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\in2csv-script.py", line 11, in <module>
    load_entry_point('csvkit==1.0.2', 'console_scripts', 'in2csv')()
  File "C:\Program Files\Python36\lib\site-packages\csvkit\utilities\in2csv.py", line 180, in launch_new_instance
    utility.run()
  File "C:\Program Files\Python36\lib\site-packages\csvkit\cli.py", line 114, in run
    self.main()
  File "C:\Program Files\Python36\lib\site-packages\csvkit\utilities\in2csv.py", line 144, in main
    table = agate.Table.from_xlsx(self.input_file, sheet=self.args.sheet, **kwar
gs)
  File "C:\Program Files\Python36\lib\site-packages\agateexcel\table_xlsx.py", line 82, in from_xlsx
    tables[sheet.title] = agate.Table(rows, column_names, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\agate\table\__init__.py", line 124, in __init__
    raise ValueError('Row %i has %i values, but Table only has %i columns.' % (i, len_row, len_column_names))
ValueError: Row 3 has 9 values, but Table only has 5 columns.
[Check_Register2.xlsx](https://github.com/wireservice/csvkit/files/1032731/Check_Register2.xlsx)

**Comment by jpmckinney** [comment]
The merged cells seem to be the issue, though if I simply save the file in Excel, the command then works. So, seems to be another issue with the software that authors the Excel file.

**Comment by dmccracken123** [comment]
I'll reach out to their support and see if they can remove the cell merging from their script. Thanks again for the help!
