### ISSUE TITLE
in2csv: Expected BOF record; found 'MIME-Ver'

### ISSUE THREAD

**Issue by rsutaria** [wireservice/csvkit#847]
Hello,

I'm trying to convert an XLS to CSV using the in2csv tool. But I get this error:

Unsupported format, or corrupt file: Expected BOF record; found 'MIME-Ver'

The file I'm trying to convert is attached here (I've zipped it as github was not allowing me to upload .xls file)

[SWM_D.xls.zip](https://github.com/wireservice/csvkit/files/1088030/SWM_D.xls.zip)

Any ideas on why the in2csv is not converting this file to csv?

**Comment by jpmckinney** [comment]
csvkit uses `xlrd` to read Excel files, and the exception is raised from `xlrd`:

```
Traceback (most recent call last):
  File "/Users/james/.pyenv/versions/csvkit3/bin/in2csv", line 11, in <module>
    load_entry_point('csvkit==1.0.2', 'console_scripts', 'in2csv')()
  File "/Users/james/.pyenv/versions/3.6.1/envs/csvkit3/lib/python3.6/site-packages/csvkit/utilities/in2csv.py", line 180, in launch_new_instance
    utility.run()
  File "/Users/james/.pyenv/versions/3.6.1/envs/csvkit3/lib/python3.6/site-packages/csvkit/cli.py", line 114, in run
    self.main()
  File "/Users/james/.pyenv/versions/3.6.1/envs/csvkit3/lib/python3.6/site-packages/csvkit/utilities/in2csv.py", line 142, in main
    table = agate.Table.from_xls(self.input_file, sheet=self.args.sheet, **kwargs)
  File "/Users/james/.pyenv/versions/3.6.1/envs/csvkit3/src/agateexcel/agateexcel/table_xls.py", line 30, in from_xls
    book = xlrd.open_workbook(file_contents=path.read())
  File "/Users/james/.pyenv/versions/3.6.1/envs/csvkit3/lib/python3.6/site-packages/xlrd/__init__.py", line 441, in open_workbook
    ragged_rows=ragged_rows,
  File "/Users/james/.pyenv/versions/3.6.1/envs/csvkit3/lib/python3.6/site-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/Users/james/.pyenv/versions/3.6.1/envs/csvkit3/lib/python3.6/site-packages/xlrd/book.py", line 1230, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/Users/james/.pyenv/versions/3.6.1/envs/csvkit3/lib/python3.6/site-packages/xlrd/book.py", line 1224, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
xlrd.biffh.XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'MIME-Ver'
```

I would raise the question on xlrd's issue tracker, but it looks like there's a problem with the Excel file.

**Comment by jpmckinney** [comment]
Actually, I can't even open the file in Excel…

**Comment by rsutaria** [comment]
The xls file is being downloaded from a government website. The file is
generated using an SAP platform:

http://r3app.mcgm.gov.in:8000/sap/bc/webdynpro/sap/zpur_order_datas

I'm attaching the xls file I've downloaded from the above SAP link.

When I try to open it using my Excel, I get this error warning:


When I click "Yes", it goes ahead & opens the xls file.

​

**Comment by jpmckinney** [comment]
I recommend you re-save the file after opening it in Excel in order to repair it, then process it with csvkit.

**Comment by rsutaria** [comment]
The problem is there are thousands of such Excel files that we are trying
to process. Hence, needed a command line solution which can be used as a
batch process.

Is there something getting added to the file header by the SAP system?

I really need a command line solution to merge some of the columns into a
single column..

RS

**Comment by jpmckinney** [comment]
If you open the XLS file in a text editor, you'll see that it's just HTML text (whereas XLS files are binary).  I think instead of processing the XLS files as XLS files, you can process them as HTML files and do the processing you need. (Or convert the HTML files to CSV files and then use csvkit.)

**Comment by rsutaria** [comment]
Damn (experiencing facepalm :)

Looks like the SAP platform setup by that government dept. is exporting XLS
files in the most weird way possible. Will write a script to process these
as HTML & not CSV files.

Appreciate your inputs on this. Thanks, once again.
