### ISSUE TITLE
error: load_workbook() got an unexpected keyword argument 'use_iterators'

### ISSUE THREAD

**Issue by gustavodiazjaimes** [wireservice/csvkit#852]
I got an error trying to use the lib

``` bash
$ in2csv-3 my_excel.xlsx > my_excel.csv
load_workbook() got an unexpected keyword argument 'use_iterators'

$ python3 -V
Python 3.5.3

$ pip show csvkit
Name: csvkit
Version: 0.9.1
Summary: A library of utilities for working with CSV, the king of tabular file formats.
Home-page: http://csvkit.rtfd.org/
Author: Christopher Groskopf
Author-email: staringmonkey@gmail.com
License: MIT
Location: /usr/lib/python3.5/site-packages
Requires: xlrd, sqlalchemy, openpyxl, six, python-dateutil
```

**Comment by jpmckinney** [comment]
Can you run the command with `-v`? (as requested here: https://github.com/wireservice/csvkit/blob/master/CONTRIBUTING.rst)

**Comment by avishekrk** [comment]
I got the same problem. Here is the output: 
```
Traceback (most recent call last):
  File "/group/dsapp-lab/miniconda3/bin/in2csv", line 6, in <module>
    sys.exit(csvkit.utilities.in2csv.launch_new_instance())
  File "/group/dsapp-lab/miniconda3/lib/python3.6/site-packages/csvkit/utilities/in2csv.py", line 82, in launch_new_instance
    utility.main()
  File "/group/dsapp-lab/miniconda3/lib/python3.6/site-packages/csvkit/utilities/in2csv.py", line 76, in main
    data = convert.convert(self.input_file, filetype, **kwargs)
  File "/group/dsapp-lab/miniconda3/lib/python3.6/site-packages/csvkit/convert/__init__.py", line 39, in convert
    return xlsx2csv(f, **kwargs)
  File "/group/dsapp-lab/miniconda3/lib/python3.6/site-packages/csvkit/convert/xlsx.py", line 51, in xlsx2csv
    book = load_workbook(f, use_iterators=True, data_only=True)
TypeError: load_workbook() got an unexpected keyword argument 'use_iterators'

```

**Comment by jpmckinney** [comment]
You're using a very old version of csvkit. Please upgrade to > 1.0.

**Comment by KamarajuKusumanchi** [comment]
A lot of people (including myself) still use old versions of csvkit. For example, anaconda still carries 0.9.1 (https://anaconda.org/anaconda/csvkit) . Would it be possible to fix this bug in 0.9.1 ?

**Comment by jpmckinney** [comment]
If you can't install the latest version with the `conda install` command, try using the `pip install` command. There is insufficient support to maintain two versions of csvkit, unfortunately.

**Comment by KamarajuKusumanchi** [comment]
No worries. FWIW, the csvkit in Anaconda is now upgraded to 1.0.2 .
[1] - https://github.com/ContinuumIO/anaconda-issues/issues/6629
