### ISSUE TITLE
Extract data from json array

### ISSUE THREAD

**Issue by sergii-rolskii** [wireservice/csvkit#864]
I have JSON like format:
```
{
  "took": 5,
  "_shards": {
     "total": 18,
    "successful": 18,
    "failed": 0
},
"hits": {
    "total": 40166,
    "max_score": 0,
    "hits": []
  },
"aggregations": {
    "3": {
      "doc_count_error_upper_bound": 27,
      "sum_other_doc_count": 39532,
      "buckets": [
      {
          "key": "5540C447F2020.AC10E74.3009D347",
          "doc_count": 30
        },
        {
          "key": "5540C466558C8.AC12341.140D236E",
          "doc_count": 29
        },
        {
          "key": "55407D5EA1B78.A80E1C8.9207E6F3",
          "doc_count": 28
        }
]}
}
```
I can get data from` _shards` or `hits` but I need get data only `buckets`
If I try: 
**`in2csv -k "buckets" -v csv/test.json`**
I get error:
```
/usr/lib/python2.7/site-packages/openpyxl-2.5.0a2-py2.7.egg/openpyxl/xml/__init__.py:15: UserWarning: The installed version of lxml is too old to be used with openpyxl
Traceback (most recent call last):
  File "/usr/bin/in2csv", line 11, in <module>
    load_entry_point('csvkit==1.0.3', 'console_scripts', 'in2csv')()
  File "build/bdist.linux-x86_64/egg/csvkit/utilities/in2csv.py", line 182, in launch_new_instance
  File "build/bdist.linux-x86_64/egg/csvkit/cli.py", line 114, in run
  File "build/bdist.linux-x86_64/egg/csvkit/utilities/in2csv.py", line 140, in main
  File "build/bdist.linux-x86_64/egg/agate/table/from_json.py", line 59, in from_json
KeyError: 'buckets'
```

What did I miss?

**Comment by jpmckinney** [comment]
`-k` takes "a **top-level** key to use look within for a list of objects to be converted when processing JSON' but `buckets` is under `3` under `aggregations`. I suggest using [`jq`](https://stedolan.github.io/jq/), like this:

    cat file.json | jq '.aggregations|.["3"].buckets' | in2csv -f json
