### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec [..] when using csvsql

### ISSUE THREAD

**Issue by epeld** [wireservice/csvkit#914]
Hi,
I am trying to use csvsql with a utf8-encoded file containing Swedish characters. I am using the `--encoding`-flag.

    $ csvsql -v  -d'|' -eutf8 -K1 --db postgresql://postgres:pw@localhost/erik_test --table bar --insert -y1000 data.csv 

but I am still getting this error:
```

Traceback (most recent call last):
  File "/usr/local/bin/csvsql", line 9, in <module>
    load_entry_point('csvkit==1.0.3', 'console_scripts', 'csvsql')()
  File "build/bdist.macosx-10.12-intel/egg/csvkit/utilities/csvsql.py", line 188, in launch_new_instance
  File "build/bdist.macosx-10.12-intel/egg/csvkit/cli.py", line 114, in run
  File "build/bdist.macosx-10.12-intel/egg/csvkit/utilities/csvsql.py", line 94, in main
  File "build/bdist.macosx-10.12-intel/egg/csvkit/utilities/csvsql.py", line 129, in _failsafe_main
  File "build/bdist.macosx-10.12-intel/egg/agate/table/from_csv.py", line 88, in from_csv
  File "build/bdist.macosx-10.12-intel/egg/agate/table/__init__.py", line 85, in __init__
  File "build/bdist.macosx-10.12-intel/egg/agate/utils.py", line 291, in deduplicate
  File "build/bdist.macosx-10.12-intel/egg/agate/warns.py", line 34, in warn_duplicate_column
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/warnings.py", line 33, in _show_warning
    file.write(formatwarning(message, category, filename, lineno, line))
  File "build/bdist.macosx-10.12-intel/egg/leather/utils.py", line 47, in <lambda>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/warnings.py", line 42, in formatwarning
    s =  "%s:%s: %s: %s\n" % (filename, lineno, category.__name__, message)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 24: ordinal not in range(128)
```
I also tried setting `PYTHONIOENCODING=utf8` but it didn't do any good. Could you help me out?
I am running this on a mac and csvsql reports version `1.0.3`. Thanks!

**Comment by dbuijs** [comment]
I see something that may be related. If it isn't please let me know and I'll submit as a separate issue. Using sql2csv to extract data from an Oracle database. 

The query works fine in SQLPlus when NLS_LANG is set to .AL32UTF8. However when I run the same query in sql2csv (with this NLS_LANG setting), I get the following error:

    Traceback (most recent call last):
      File "/usr/local/bin/sql2csv", line 11, in <module>
        load_entry_point('csvkit==1.0.2', 'console_scripts', 'sql2csv')()
      File "/usr/local/lib/python2.7/dist-packages/csvkit/utilities/sql2csv.py", line 73, in 
    launch_new_instance
        utility.run()
      File "/usr/local/lib/python2.7/dist-packages/csvkit/cli.py", line 114, in run
        self.main()
      File "/usr/local/lib/python2.7/dist-packages/csvkit/utilities/sql2csv.py", line 66, in main
        output.writerow(row)
      File "/usr/local/lib/python2.7/dist-packages/agate/csv_py2.py", line 190, in writerow
        UnicodeWriter.writerow(self, row)
      File "/usr/local/lib/python2.7/dist-packages/agate/csv_py2.py", line 103, in writerow
        self.writer.writerow([six.text_type(s if s is not None else '').encode(self.encoding) for s in row])
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

If I run the same sql2csv command without NLS_LANG set, it runs fine, but all the accented characters are coerced to ASCII. This behaviour doesn't seem to change if I add `?coerce_unicode=False` to the connection string. 

Any thoughts? Should I be looking at SqlAlchemy or CX-Oracle instead?

**Comment by jpmckinney** [comment]
Can you share a minimal version of data.csv that reproduces the error?
