### ISSUE TITLE
Multiple UnicodeDecodeError when testing with Python 3.6

### ISSUE THREAD

**Issue by ghisvail** [wireservice/csvkit#926]
In an attempt to update the Debian packaging to the latest released version, the build currently fails at the testing stage due to multiple `UnicodeDecodeError`s being raised. Please check out the complete log attached to this post.

The errors are of the form:
```text
[csvkit_1.0.2-1_amd64.build.zip](https://github.com/wireservice/csvkit/files/1671789/csvkit_1.0.2-1_amd64.build.zip)

======================================================================
ERROR: test_convert_json (tests.test_utilities.test_in2csv.TestIn2CSV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/csvkit-1.0.2/.pybuild/pythonX.Y_3.6/build/tests/test_utilities/test_in2csv.py", line 60, in test_convert_json
    self.assertConverted('json', 'examples/testjson.json', 'examples/testjson_converted.csv')
  File "/build/csvkit-1.0.2/.pybuild/pythonX.Y_3.6/build/tests/test_utilities/test_in2csv.py", line 26, in assertConverted
    self.assertEqual(output, f.read())
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 295: ordinal not in range(128)
```

**Comment by ghisvail** [comment]
It passes if a unicode locale is set `LC_ALL=C.UTF-8`.

Debian builds default to `LC_ALL=C`.

**Comment by jpmckinney** [comment]
Hmm, I think it's that Python adopts the environment's encoding for the strings it prints to standard output, but it can't print UTF-8 to ASCII and thus fails.

I don't know anything about Debian builds, but is it possible to set environment variables like `PYTHONIOENCODING=utf8` ?

**Comment by ghisvail** [comment]
Debian builds use standard Makefiles, so yes I can pass environment variables. Actually I made the tests pass by explicitly setting `LC_ALL=C.UTF8`.
